/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

package mozilla.components.lib.crash.service

/**
 * Holds annotation keys used by crash reporting services. Each enum value
 * carries the string name sent in the crash report payload.  Defined here so
 * the various crash services (Socorro, Sentry, Glean) can reference a single,
 * stable set of annotation names without depending on code generated by the
 * Mozilla monorepo's full build pipeline.
 */
object CrashReport {
    enum class Annotation(val value: String) {
        ProductName("ProductName"),
        ProductID("ProductID"),
        Version("Version"),
        ApplicationBuildID("ApplicationBuildID"),
        AndroidComponentVersion("AndroidComponentVersion"),
        GleanVersion("GleanVersion"),
        ApplicationServicesVersion("ApplicationServicesVersion"),
        GeckoViewVersion("GeckoViewVersion"),
        BuildID("BuildID"),
        Vendor("Vendor"),
        Breadcrumbs("Breadcrumbs"),
        useragent_locale("useragent_locale"),
        DistributionID("DistributionID"),
        CrashEventID("CrashEventID"),
        JavaStackTrace("JavaStackTrace"),
        JavaException("JavaException"),
        CrashTime("CrashTime"),
        CrashType("CrashType"),
        StartupTime("StartupTime"),
        ReleaseChannel("ReleaseChannel"),
        Android_ProcessName("Android_ProcessName"),
        Android_PackageName("Android_PackageName"),
        Android_Version("Android_Version"),
        Android_Manufacturer("Android_Manufacturer"),
        Android_Model("Android_Model"),
        Android_Hardware("Android_Hardware"),
        Android_Device("Android_Device"),
        Android_Brand("Android_Brand"),
        Android_Display("Android_Display"),
        Android_Board("Android_Board"),
        Android_CPU_ABI("Android_CPU_ABI"),
        Android_CPU_ABI2("Android_CPU_ABI2"),
        Android_Fingerprint("Android_Fingerprint"),
        InstallTime("InstallTime"),
        additional_minidumps("additional_minidumps"),
        ProcessType("ProcessType"),
        MinidumpSha256Hash("MinidumpSha256Hash"),
        RemoteType("RemoteType");

        override fun toString(): String = value
    }
}
